# Generated by Django 4.2.5 on 2023-11-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_productorder_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
    ]
